### ISSUE TITLE
ARIES Subcategories

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#79]
There may already be an issue on this, but it's been almost a week, so I figured I would report in case it isn't being addressed. Max and I added the new ARIES products to the admin last week, as well as new subcategories to display them. We added 6.5 IN RidgeStep running boards, 5.5 IN AdvantEDGE side bars, 5.5 IN AdvantEDGE bull bars, AdvantEDGE headache racks and Jeep rocker steps. The categories and parts still are not showing up on the live website, even though everything is loaded into the admin and the parts (I believe all of them) are status 800. Also, the 2.5 IN bull bars categories is showing up, though I see it's disabled in the admin. This may be a caching issue.

**Comment by ninnemana** [comment]
I "saved" the Sides category in the admin and the categories are showing up. Looks like some of the part data is pretty empty, but I think that's a problem that was introduced elsewhere. @aaronrodgersmoustache can you verify this is fixed?

**Comment by aaronrodgersmoustache** [comment]
All the categories are showing up with parts in them, except for Jeep Rocker Steps (344). Also, 2.5 IN bull bars is still appearing, and many of the categories are out of order, including the main categories in the dropdown menu. This isn't a huge deal, but is this something that John's sorting tool can fix?

**Comment by aaronrodgersmoustache** [comment]
AdvantEDGE headache racks (343) also isn't showing up.

**Comment by ninnemana** [comment]
All categories are showing up now.

**Comment by stinkyfingers** [comment]
I hate how the sort works. Hacky. Will revisit.

**Comment by ninnemana** [comment]
Re-opening or no?

**Comment by aaronrodgersmoustache** [comment]
The category sort works for CURT but still doesn't seem to be working for ARIES. I ordered them in the admin, and they remained unaffected on the website. I tried saving each category after ordering it, but that didn't work either. I also waited for a 24-hour period to pass to make sure it wasn't a caching issue, and that doesn't seem to be the case either. I did notice that when I saved each category under Edit, the sorting would be reset to zero. Also, the 2.5 IN bull bar category is still showing up. This is an issue with the disable feature. Should I make a separate issue?
![aries categories out of order](https://cloud.githubusercontent.com/assets/11280480/11729082/0adf8606-9f53-11e5-9070-e431cb6272ce.JPG)

**Comment by stinkyfingers** [comment]
Disabling: 2b2e736

**Comment by baseigneurie** [comment]
It seems like we might have fixed the sort issue, but we're still working on disabling categories.

Also, remember to save the parent category to make sure your changes are reflected on the live site.

**Comment by ninnemana** [comment]
So the only thing left is getting the 2.5 IN Bull Bar removed, by allowing the fan-out process to support category deletion. Correct?

**Comment by aaronrodgersmoustache** [comment]
I still don't think the sorting is working properly. I tried saving the parent category, but the subcategories are still not taking on the website. Also, yes, 2.5 bull bars needs to be removed.

**Comment by ninnemana** [comment]
Right now it's as follows:

```
3 IN Bull Bars
2.5 IN Bull Bars, Sport Bar (needs to be deleted)
3 IN Bull Bars, Pro Series
5.5 In Bull Bars, AdvantEdge
Grille Guards
Grille Guards, Pro Series
4 IN Bull Bars, Big Horn
```
and you'd like it to be:

```
3 IN Bull Bars
3 IN Bull Bars, Pro Series
3 IN Bull Bars, Stealth
4 IN Bull Bars, Big Horn
5.5 IN Bull Bars, AdvantEDGE
Grille Guards
Grille Guards, Pro Series
```

Correct?

**Comment by aaronrodgersmoustache** [comment]
Correct

**Comment by aaronrodgersmoustache** [comment]
It looks like the subcategory sorting is fixed, and I'm no longer seeing 2.5 IN bull bars. Before we close this issue, could we iron out the order of the five main categories. I would like sort them to correspond to the catalog. The order should be as follows:

Front Ends
Sides
Accessories
Jeep
Interior

Also, I talked with Joe R, and we agreed that Application Guides should be more distinguished from the rest of the menu. Could you please change the color of the font to black?

Thanks!

**Comment by ninnemana** [comment]
@aaronrodgersmoustache you've met your request quota for the week, backlogged until further review.

**Comment by aaronrodgersmoustache** [comment]
Could we revisit this? The subcategory sorting feature seems to be working well but the main categories cannot be sorted in the admin. They should be in the following order:

Front Ends
Sides
Accessories
Jeep
Interior
